### ISSUE TITLE
What is the improper setting ?

### ISSUE THREAD

**Issue by Guzaiwang** [lsa1997/POP#2]
As mentioned in your model readme file,  "Note that all models are trained based on the released code. We fix an improper setting in the cropping operation and achieve results better than those reported in our paper." I would like to know what is the improper setting and how to fix it.

Thanks

**Comment by lsa1997** [comment]
You can check the details [here](https://github.com/lsa1997/POP/commit/b8f0b3a454fe835e1c0bd759c28475e03159851e). We just remove the code checking _fg_remain_ratio_. The initial code is used for standard few-shot segmentation, where we check _fg_remain_ratio_ to retain enough foreground pixels (_target_cls_=1) for binary segmentation. However, it is an improper setting for GFSS since there are multiple foreground classes.
